name: Keep Alive

on:
  schedule:
    - cron: "0 2 * * *"  # 7:30 AM IST
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Keep repo active
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 20
